---
title: "Data Analysis: Stable School"
author: 'Anna Heiting'
output:
  html_document: default
--- 

```{r data-and-packages}
#install.packages("tidyverse")
library(tidyverse)
#install.packages("readxl")
library(readxl)
#install.packages("googlesheets4")
library(googlesheets4)
#install.packages("likert")
library(likert)
#install.packages("ggpattern")
library(ggpattern)

#Google sheet Quantitative Analysis
sheet_url <- "https://docs.google.com/spreadsheets/d/1ztEGQVx6-yxLz587DlWl6xOpdQvGJrqjYMRathBrU18/edit?usp=sharing"

# List all sheets in the Google Sheets document
sheets <- sheet_names(sheet_url)

# Read each sheet into a separate data frame
All <- read_sheet(sheet_url, sheet = sheets[1])
Q8dt <- read_sheet(sheet_url, sheet = sheets[2])
Q8eng <- read_sheet(sheet_url, sheet = sheets[3])

All_count_per <- read_sheet(sheet_url, sheet = sheets[5])
All_count_per_dt <- read_sheet(sheet_url, sheet = sheets[6])

#Google sheet Analysis Round 1 vs 2
sheet_url_2 <- "https://docs.google.com/spreadsheets/d/1WbHRXo-EqNfVzVspCKtWQGQGTzorj_MdHArB2Pt1kx8/edit?usp=sharing"

sheets2 <- sheet_names(sheet_url_2)

Round1eng <- read_sheet(sheet_url_2, sheet = sheets2[1])
Round2eng <- read_sheet(sheet_url_2, sheet = sheets2[2])
Runde1 <- read_sheet(sheet_url_2, sheet = sheets2[3])
Runde2<- read_sheet(sheet_url_2, sheet = sheets2[4])

#Google sheet Maßnahmenumsetzung
sheet_url_3 <- "https://docs.google.com/spreadsheets/d/1RfVEZXy_h4y9lHYxk92XjMpXt2x7T61qYMPzONCc-bA/edit?usp=sharing"

sheets3 <- sheet_names(sheet_url_3)

Implementation_dt <- read_sheet(sheet_url_3, sheet = sheets3[1])
Implementation_eng <- read_sheet(sheet_url_3, sheet = sheets3[2])

```

``` {r convert-to-factor}
#All questions
#deutsch
All_dt_factor <- All %>%
  na.omit() %>%
  as.data.frame() %>%
  mutate(across(everything(), 
                ~ factor(.x, 
                          levels = c(5, 4, 3, 2, 1), 
                          labels = c("Stimme gar nicht zu", "Stimme nicht zu", "Neutral", "Stimme zu", "Stimme sehr zu"))))

#english
All_eng_factor <- All %>%
  mutate(across(everything(), 
                ~ factor(.x, 
                          levels = c(5, 4, 3, 2, 1), 
                          labels = c("Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"))))


#Question 8
#deutsch
Q8dt_factor <- Q8dt %>%
  mutate(across(everything(), 
                ~ factor(.x, 
                          levels = c(5, 4, 3, 2, 1), 
                          labels = c("Stimme gar nicht zu", "Stimme nicht zu", "Neutral", "Stimme zu", "Stimme sehr zu"))))

#english
Q8eng_factor <- Q8eng %>%
  mutate(across(everything(), 
                ~ factor(.x, 
                          levels = c(5, 4, 3, 2, 1), 
                          labels = c("Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"))))
```

``` {r likert-All_dt_factor}
likert_All_dt <- likert(All_dt_factor, nlevels = 5) %>%
  summary() %>%
  as.data.frame()
```

<b>Implementation of measures<b>

```{r 1.2-dt}

Implementation_dt$Umsetzung <- factor(Implementation_dt$Umsetzung, levels = c("gar nicht", "teilweise", "vollständig", "zukünftig"))

#Runde 1
#Umsetzung1 <- 
Implementation_dt %>%
  filter(Runde == 1) %>%
  ggplot(aes(x = Umsetzung, 
             y = Anzahl, 
             fill = `Problemfeld/Maßnahme`)) +
  geom_bar(position = "stack", stat = "identity") +
  theme_minimal() +
  scale_fill_viridis_d()

#ggsave("Umsetzung1.png", plot = Umsetzung1, width = 10, height = 6, dpi = 300)

#Runde 2
#Umsetzung2 <-
Implementation_dt %>%
  filter(Runde == 2) %>%
  ggplot(aes(x = Umsetzung, 
             y = Anzahl, 
             fill = `Problemfeld/Maßnahme`)) +
  geom_bar(position = "stack", stat = "identity") +
  ylim(0, 10) +
  theme_minimal() +
  scale_fill_viridis_d() +
  scale_x_discrete(drop = FALSE)

#ggsave("Umsetzung2.png", plot = Umsetzung2, width = 10, height = 6, dpi = 300)
```

```{r 1.2-eng}

Implementation_eng$Implementation <- factor(Implementation_eng$Implementation, levels = c("not at all", "partly", "complete", "in the future"))

#Round 1
#Implementation1 <- 
Implementation_eng %>%
  filter(Round == 1) %>%
  ggplot(aes(x = Implementation, 
             y = Count, 
             fill = `Problem area/Measure`)) +
  geom_bar(position = "stack", stat = "identity") +
  theme_minimal() +
  scale_fill_viridis_d()

#ggsave("Implementation1.png", plot = Implementation1, width = 10, height = 6, dpi = 300)

#Round 2
#Implementation2 <-
Implementation_eng %>%
  filter(Round == 2) %>%
  ggplot(aes(x = Implementation, 
             y = Count, 
             fill = `Problem area/Measure`)) +
  geom_bar(position = "stack", stat = "identity") +
  ylim(0, 10) +
  theme_minimal() +
  scale_fill_viridis_d() +
  scale_x_discrete(drop = FALSE)

#ggsave("Implementation2.png", plot = Implementation2, width = 10, height = 6, dpi = 300)
```

<b>Likert bar plots in English</b>

``` {r likert-plot-all-questions}
All_likert <- likert(Item~., All_count_per)
plot(All_likert, ylab = "Question")
```

```{r likert-plot-1.3}
Per1.3 <- subset(All_count_per, Item == "How did you like the concept 'Stable School'?") %>%
  rename('Very bad' = 'Strongly Disagree', 
         'Bad' = 'Disagree', 
         'Good' = 'Agree', 
         'Very good' = 'Strongly agree')

likert1.3 <- likert(Item~., Per1.3)

plot(likert1.3)
```

```{r likert-plot-1.4-1.6}
Per1.4_1.6 <- subset(All_count_per, Item %in% c("How high do you estimate, was the benefit of the 'Stable School' regarding calf health on your farm?", 
                                                "How high do you estimate, was the benefit of the 'Stable School' regarding employee management and efficiency on your farm?", 
                                                "How high do you estimate, was the benefit of the 'Stable School' in general on your farm?")) %>%
  rename('Useless' = 'Strongly Disagree', 
         'Low use' = 'Disagree', 
         'Useful' = 'Agree', 
         'Very useful' = 'Strongly agree')

likert1.4_1.6 <- likert(Item~., Per1.4_1.6)

plot(likert1.4_1.6)
```

```{r likert-plot-1.8}
likert1.8 <- likert(Item~., Q8eng)

plot(likert1.8)
```

```{r likert-plot-1.9-1.10}
Per1.9_1.10 <- subset(All_count_per, Item %in% c("Would you say that the 'Stable School' increased your awareness regarding calf health problems on the farm?", 
                                                "Would you say that the 'Stable School' increased your awareness regarding employee management problems on the farm?"))

likert1.9_1.10 <- likert(Item~., Per1.9_1.10)

plot(likert1.9_1.10)
```

```{r likert-plot-2.1-2.2}
Per2.1_2.2 <- subset(All_count_per, Item %in% c("In comparison to other advising services, how motivating was the 'Stable School' for you to change the calf health situation on your farm?", 
                                                "In comparison to other advising services, how motivating was the 'Stable School' for you to change the employee management situation on your farm?")) %>%
  rename('Demotivating' = 'Strongly Disagree', 
         'Less motivating' = 'Disagree', 
         'Motivating' = 'Agree', 
         'Very motivating' = 'Strongly agree')

likert2.1_2.2 <- likert(Item~., Per2.1_2.2)

plot(likert2.1_2.2)
```

```{r likert-plot-2.9}
Per2.9 <- subset(All_count_per, Item == "How important was the social aspect of the 'Stable School' for you?") %>%
  rename('Unimportant' = 'Strongly Disagree', 
         'Very unimportant' = 'Disagree', 
         'Important' = 'Agree', 
         'Very important' = 'Strongly agree')

likert2.9 <- likert(Item~., Per2.9)

plot(likert2.9)
```

``` {r likert plot Round 1vs2}
#Round 1
likertRound1eng <- likert(Item~., Round1eng)

plot(likertRound1eng)

#Round 2
likertRound2eng <- likert(Item~., Round2eng)

plot(likertRound2eng)

```

<b>Likert bar plots auf deutsch</b>

``` {r likert-plot-all-questions-dt}
All_likert_dt <- likert(Item~., All_count_per_dt)
plot(All_likert_dt, ylab = "Question")
```

```{r likert-plot-1.3_dt}
Per1.3_dt <- subset(All_count_per_dt, Item == "Wie gefiel Ihnen grundsätzlich der hier im Projekt gewählte Ansatz?") %>%
  rename('Sehr schlecht' = 'Stimme gar nicht zu', 
         Schlecht = 'Stimme nicht zu', 
         Gut = 'Stimme zu', 
         'Sehr gut' = 'Stimme sehr zu')

likert1.3_dt <- likert(Item~., Per1.3_dt)

plot(likert1.3_dt)
```

```{r likert-plot-1.4-1.6_dt}
Per1.4_1.6_dt <- subset(All_count_per_dt, Item %in% c("Wie hoch würden Sie den Nutzen von der 'Stallschule' im Hinblick auf die Verbesserung der Kälbergesundheit im eigenen Betrieb einschätzen?", 
                                                "Wie hoch würden Sie den Nutzen von der 'Stallschule' im Hinblick auf die Verbesserung der Mitarbeiterführung im eigenen Betrieb einschätzen?", 
                                                "Wie hoch würden Sie den Nutzen von der 'Stallschule im Allgemeinen für Ihren eigenen Betrieb einschätzen?")) %>%
  rename('Kein Nutzen' = 'Stimme gar nicht zu', 
         'Geringer Nutzen' = 'Stimme nicht zu', 
         'Hoher Nutzen' = 'Stimme zu', 
         'Sehr hoher Nutzen' = 'Stimme sehr zu')

likert1.4_1.6_dt <- likert(Item~., Per1.4_1.6_dt)


plot(likert1.4_1.6_dt)
```

```{r likert-plot-1.8dt}
Q8dt$Item <- factor(Q8dt$Item, levels = unique(Q8dt$Item))

likert1.8_dt <- likert(Item~., Q8dt)

plot(likert1.8_dt)
```

```{r likert-plot-1.9-1.10_dt}
Per1.9_1.10_dt <- subset(All_count_per_dt, 
                         Item %in% c("Würden Sie sagen, dass Ihr Problembewusstsein bzgl. der Kälbergesundheitssituation im Betrieb über die Teilnahme an den 'Stallschule'-Treffen gefördert wurde?", 
                                     "Würden Sie sagen, dass Ihr Problembewusstsein bzgl. der Mitarbeiterführungssituation im Betrieb über die Teilnahme an den 'Stallschule'-Treffen gefördert wurde?")) %>%
  rename('Gar nicht' = 'Stimme gar nicht zu', 
         'Weniger deutlich' = 'Stimme nicht zu', 
         'Deutlich' = 'Stimme zu', 
         'Sehr deutlich' = 'Stimme sehr zu')

likert1.9_1.10_dt <- likert(Item~., Per1.9_1.10_dt)

plot(likert1.9_1.10_dt)
```

```{r likert-plot-2.1-2.2_dt}
Per2.1_2.2_dt <- subset(All_count_per_dt, Item %in% c("Im Vergleich mit anderen Beratungsmöglichkeiten zur Verbesserung der Kälbergesundheitssituation: Wie motivierend bewerten Sie das Instrument 'Stallschule'?", 
                                                "Im Vergleich mit anderen Beratungsmöglichkeiten zur Verbesserung der Mitarbeiterführungssituation: Wie motivierend bewerten Sie das Instrument 'Stallschule'?")) %>%
  rename('Sehr viel motivierender' = 'Stimme gar nicht zu', 
         'Motivierender' = 'Stimme nicht zu', 
         'Weniger motivierend' = 'Stimme zu', 
         'Demotivierend' = 'Stimme sehr zu')

likert2.1_2.2_dt <- likert(Item~., Per2.1_2.2_dt)

plot(likert2.1_2.2_dt)
```

```{r likert-plot-2.9_dt}
Per2.9_dt <- subset(All_count_per_dt, Item == "Wie wichtig war für Sie der soziale Aspekt der 'Stallschule'?") %>%
  rename('Sehr unwichtig' = 'Stimme gar nicht zu', 
         'Unwichtig' = 'Stimme nicht zu', 
         'Wichtig' = 'Stimme zu', 
         'Sehr wichtig' = 'Stimme sehr zu')

likert2.9_dt <- likert(Item~., Per2.9_dt)

plot(likert2.9_dt)
```

``` {r likert plot Runde 1vs2}
#Runde 1
likertRunde1 <- likert(Item~., Runde1)

plot(likertRunde1)

#Runde 2
likertRunde2 <- likert(Item~., Runde2)

plot(likertRunde2)

```